name: scrape
on:
  schedule: [{ cron: "15 * * * *" }] # 毎時15分
  workflow_dispatch:
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm init -y
      - run: npm i cheerio
      - run: node scripts/scrape-kashiwa.js
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add docs/data/news.json
          git commit -m "update news" || exit 0
          git push