name: Update Kashiwa News
on:
  schedule:
    - cron: '0 0 * * *' # 毎日午前9時(JST)に実行
  workflow_dispatch:   # 手動実行ボタンを有効化

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install axios cheerio
      - run: node scrape.js
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public